### ISSUE TITLE
Right clicking messages media

### ISSUE THREAD

**Issue by PaddiM8** [17hoehbr/Discord-M1#6]
On the regular Discord client, you are able to right click messages to reply to them, add reactions, and more. You are also able to right click things like images in order to copy them or their link. This doesn't work with Nativefier, since the web version doesn't seem to show the context menus for this. Maybe it would be possible to trigger these to open somehow? They probably exist, but lack events to trigger them?

**Comment by bryce-hoehn** [comment]
Thanks for pointing that out, I'll take a look at it when I get a chance. For now though it seems like you can still access all of the functions by hovering over the message and clicking the ... button on the left side of the message.

**Comment by PaddiM8** [comment]
@17hoehbr Yeah you can access most things by clicking the ... button, but it's a bit harder to get that right compared to just right clicking a message. I also haven't found a way like this to copy media. Hopefully it can be done, but I guess it may be a bit complicated since it needs to know which specific message/image/video you right click and all.

**Comment by PaddiM8** [comment]
I did some digging, and it looks like the event is fired, but it only shows the context menu if you're on a desktop client. It checks if you're on a desktop client by checking if window.DiscordNative exists (it's null on web, but not on desktop clients). Unfortunately, just giving this a value isn't enough, since this check seems to only be done during load or something, and even if you add it before load, it breaks, because it tries to do desktop client things. Only way I can think of to solve this would be to actually edit the source code, but I don't know if that's doable...

```js
if (y.default.embedded && !f) {
```
y.default contains functions like isOSX(), which seem to be located here:
```js
var i = window.DiscordNative,
    o = null != i,
    a = null != i ? i.process.platform : '',
    s = {
      PlatformTypes: r,
      embedded: o,
      platform: a,
      isWindows: function () {
        return /^win/.test(a)
      },
      isOSX: function () {
        return 'darwin' === a
      },
      isLinux: function () {
        return 'linux' === a
      },
      isDesktop: function () {
        return this.isWindows() || this.isOSX() || this.isLinux()
      },
      isIOS: function () {
        return !1
      },
      isWeb: function () {
        return !this.isIOS() && this.getPlatform() === r.WEB
      },
      isAndroidChrome: function () {
        return null != navigator.userAgent && null != navigator.userAgent.toLowerCase().match('(android ).+chrome/[.0-9]* mobile')
      },
      isAndroid: function () {
        var e;
        return null != (null === (e = navigator.userAgent) || void 0 === e ? void 0 : e.match(/android/i))
      },
      getPlatform: function () {
        return this.isWindows() ? r.WINDOWS : this.isOSX() ? r.OSX : this.isLinux() ? r.LINUX : r.WEB
      },
      hasFocus: function () {
        return document.hasFocus()
      }
    };
```

Damn it!

**Comment by bryce-hoehn** [comment]
Damn, yeah anything that is not supported by the web client in general will not work in this app either. As for copying media though a workaround that I found is that you can left click on the image, then click "Open Original". This will open a new electron window with the image in full screen view. You still cannot right click on it for some reason but if you press the "Edit" dropdown on the menu bar you will have the option to copy, which when selected will copy the image to your clipboard. It's a bit tedious but it works.

It does seem like the web version is able to right click on the enlarged image and copy it from there though without having to click open original or go through the edit bar so it might be possible to at least get the right click dialog to show up on enlarged images.

**Comment by 17hoehbr** [comment]
Okay scratch that apparently clicking open original actually just opens a new electron window that also does not have right click capabilities

**Comment by PaddiM8** [comment]
Yeah, nice, images seem to be copy-able like that. That's a good workaround for now.

I actually managed to make it show a context menu when you right click messages! It's a bit hacky, but it works. It simulates a button click on the "..." button, and quickly moves the button to your cursor and back again (you don't notice it), so that the menu shows up at the cursor. I also had to make it add the "Add Reaction" item to the context menu, since this doesn't exist in the normal one when you press the "..." button. I'll probably make a pull request soon if that's alright, but will look a bit at context menus for media first and see if that can be done quickly with similar tricks. Otherwise, yeah, would probably be possible to make a custom one!

**Comment by bryce-hoehn** [comment]
I'm loving the recent merge request, though I'm reopening the issue because there is still no menu when you right click on an image you have already left clicked on (i.e. no right click menu on enlarged images). Not a big deal but it seems like we're getting fairly close to client parity and I'd like to keep it as close as possible function wise.

**Comment by bryce-hoehn** [comment]
Another minor issue I've noticed is that on the desktop client it always makes sure that the context menu doesn't go off the screen so it will dynamically adjust where the menu is positioned based on the image's position relative to the bottom of the screen. But in this version it's possible for the new settings to appear under the screen and become unaccessible. For the most recently posted image you can't get to the Copy Link/Open Link setting at all unless you right click from the very top of the image, if it's large enough anyway.

**Comment by PaddiM8** [comment]
Ah yes that's true! Should be doable

**Comment by bryce-hoehn** [comment]
#8

**Comment by BLahz** [comment]
This is default behavior for apps not signed by Apple's developer certificate. It is very easy to go around, as instructed [here](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac)
